### ISSUE TITLE
Rackspace environment crashing

### ISSUE THREAD

**Issue by blacksun1** [neillturner/ec2dream#6]
## Error

Logging into Rackspace environment, accessing a server does not work. Here is the console log of the operation.

```
EC2DREAM_HOME set to /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/executable-hooks-1.3.2
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/executable-hooks-1.3.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/bundler-unload-1.0.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rubygems-bundler-1.4.4/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/fxruby-1.6.29
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fxruby-1.6.29/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/mixlib-shellout-2.1.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/net-scp-1.2.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rubyzip-1.1.7/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/zip-zip-0.3/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/gchartrb-0.8/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/excon-0.45.4/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/formatador-0.2.5/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/mime-types-2.6.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-core-1.32.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-json-1.0.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/mini_portile-0.6.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/nokogiri-1.6.6.2
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-xml-0.1.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ipaddress-0.8.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-atmos-0.1.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-aws-0.7.4/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/inflecto-0.0.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-brightbox-0.9.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-dynect-0.0.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-ecloud-0.1.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-google-0.0.7/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-local-0.2.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-powerdns-0.1.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-profitbricks-0.0.5/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-radosgw-0.0.4/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-riakcs-0.1.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-sakuracloud-1.0.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-serverlove-0.1.2/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-softlayer-0.4.7/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-storm_on_demand-0.1.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-terremark-0.1.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/CFPropertyList-2.3.1/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fission-0.5.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-vmfusion-0.1.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-voxel-0.1.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fog-1.33.0/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/x86_64-darwin14
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/vendor_ruby/2.2.0
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/vendor_ruby/2.2.0/x86_64-darwin14
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/vendor_ruby
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/x86_64-darwin14
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5
main.initialize x86_64-darwin14
EC2_Kitchen.initialize
Settings.initialize
Settings.load_system
environment.initial_load
Initial Environment Rackspace
Auto Loaded? false
environment.load_empty_env
environment.reset_connection
Settings.put_system ENVIRONMENT
Settings.put_system AUTO
Launch.clear_panel
tree.cache.load_empty
main.tree_process
Settings.put_system ENVIRONMENT
Settings.save_system
ENVIRONMENT=Rackspace
AUTO=false
REPOSITORY_LOCATION=/Users/bruces/.ec2dream
REPOSITORY_REMOTE=/Users/bruces/.ec2dream
EXTERNAL_EDITOR=xterm -e /Applications/TextEdit.app/Contents/MacOS/TextEdit
EXTERNAL_BROWSER=open
TIMEZONE=UTC
TERMINAL_EMULATOR=xterm
environment.reset_connection
environment.load_env
environment.reset_connection
Launch.clear_panel
Settings.load
Settings.load_panel EC2_PLATFORM
Settings.load_panel EC2_URL
Settings.load_panel EC2_SSH_USER
Settings.load_panel EC2_SSH_PRIVATE_KEY
Settings.load_panel AMAZON_ACCOUNT_ID
Settings.load_panel AMAZON_ACCESS_KEY_ID
Settings.load_panel AMAZON_SECRET_ACCESS_KEY
Settings.load_panel TEST_KITCHEN_PATH
Settings.load_panel KITCHEN_YAML
Settings.load_panel VAGRANT_REPOSITORY
Settings.load_panel AVAILABILITY_ZONE
Settings.load_panel AMAZON_NICKNAME_TAG
Settings.load_panel TERMINAL_EMULATOR
Settings.load_panel SSL_CERT_FILE
tree.cache.load Rackspace
tree.cache.load_empty
ServerCache.refreshServerTree
SecGrps.load_secGrps_tags
environment.tags
Data_tags.initialize
environment.connection
Platform openstack_rackspace
ERROR: getting all tags  undefined method `describe_tags' for #<Fog::Compute::RackspaceV2::Real:0x007fff03292020>
environment.security_group
data_security_group.initialize
environment.connection
Platform openstack_rackspace
environment.addresses
Data_addresses.initialize
environment.connection
Platform openstack_rackspace
ERROR: getting all Addresses  undefined method `addresses' for #<Fog::Compute::RackspaceV2::Real:0x007fff03292020>
environment.servers
Data_servers.initialize
environment.connection
Platform openstack_rackspace
Tree.refresh_launch
main.tree_process
Launch.load
Launch.load_ops
Launch.clear_ops_panel
/Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/EC2_Launch_ops.rb:202:in `ops_clear': undefined method `text=' for nil:NilClass (NoMethodError)
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/EC2_Launch_ops.rb:166:in `clear_ops_panel'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/EC2_Launch_ops.rb:97:in `load_ops'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/EC2_Launch_ec2.rb:352:in `load'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/EC2_Main.rb:253:in `process_server'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/EC2_Main.rb:202:in `tree_second_level'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/EC2_Main.rb:145:in `tree_process'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/EC2_Main.rb:108:in `block in initialize'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fxruby-1.6.29/lib/fox16/responder2.rb:55:in `call'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fxruby-1.6.29/lib/fox16/responder2.rb:55:in `onHandleMsg'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/ec2dream.rb:22:in `selectItem'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/ec2dream.rb:22:in `run'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/lib/ec2dream.rb:22:in `initialize'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/bin/ec2dream:16:in `new'
	from /Users/bruces/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/ec2dream-4.0.5/bin/ec2dream:16:in `<top (required)>'
	from /Users/bruces/.rvm/gems/ruby-2.2.3/bin/ec2dream:23:in `load'
	from /Users/bruces/.rvm/gems/ruby-2.2.3/bin/ec2dream:23:in `<main>'
	from /Users/bruces/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/bruces/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

## Tested environment

OS: OS X Yosemite 10.10.5
Ruby: `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]` installed with `rvm`.
Version: v4.0.5
Running as root (`sudo -s`)

## How to reproduce

1. Create a valid Rackspace env
2. Click on an existing server.
3. Boom!

**Comment by neillturner** [comment]
coded this but still need to test
